package cmd

import (
	"fmt"
	"strings"
	"time"

	"github.com/spf13/cobra"

	"github.com/firefly-engineering/firefly-forage/packages/forage-ctl/internal/agent"
)

var claudeCmd = &cobra.Command{
	Use:   "claude",
	Short: "Claude agent management",
}

var claudeTokenCmd = &cobra.Command{
	Use:   "token",
	Short: "Manage Claude OAuth token for sandboxes",
}

var claudeTokenStoreCmd = &cobra.Command{
	Use:   "store <token>",
	Short: "Store a long-lived Claude OAuth token",
	Long: `Store a long-lived OAuth token generated by 'claude setup-token'.

The token is valid for 1 year and is used to authenticate Claude Code
inside sandboxes, which cannot access the host keychain.

To generate a token:
  1. Run: claude setup-token
  2. Complete the browser authentication
  3. Copy the token and run: forage-ctl claude token store <token>`,
	Args: cobra.ExactArgs(1),
	RunE: runClaudeTokenStore,
}

var claudeTokenStatusCmd = &cobra.Command{
	Use:   "status",
	Short: "Show Claude OAuth token status",
	RunE:  runClaudeTokenStatus,
}

var claudeTokenRemoveCmd = &cobra.Command{
	Use:   "remove",
	Short: "Remove stored Claude OAuth token",
	RunE:  runClaudeTokenRemove,
}

func init() {
	rootCmd.AddCommand(claudeCmd)
	claudeCmd.AddCommand(claudeTokenCmd)
	claudeTokenCmd.AddCommand(claudeTokenStoreCmd)
	claudeTokenCmd.AddCommand(claudeTokenStatusCmd)
	claudeTokenCmd.AddCommand(claudeTokenRemoveCmd)
}

func claudeTokenStore() *agent.TokenStore {
	return agent.NewTokenStore(paths().StateDir)
}

func runClaudeTokenStore(cmd *cobra.Command, args []string) error {
	token := strings.TrimSpace(args[0])
	if token == "" {
		return fmt.Errorf("token cannot be empty")
	}

	store := claudeTokenStore()
	st, err := store.Store(token)
	if err != nil {
		return fmt.Errorf("failed to store token: %w", err)
	}

	logSuccess("Token stored (expires %s)", st.ExpiresAt.Format("2006-01-02"))
	return nil
}

func runClaudeTokenStatus(cmd *cobra.Command, args []string) error {
	store := claudeTokenStore()
	status, st, err := store.Status()
	if err != nil {
		return fmt.Errorf("failed to check token: %w", err)
	}

	switch status {
	case agent.TokenMissing:
		logInfo("No Claude OAuth token stored")
		fmt.Println("  Generate one with: claude setup-token")
		fmt.Println("  Then store it with: forage-ctl claude token store <token>")
	case agent.TokenExpired:
		logWarning("Token expired on %s", st.ExpiresAt.Format("2006-01-02"))
		fmt.Println("  Generate a new one with: claude setup-token")
		fmt.Println("  Then store it with: forage-ctl claude token store <token>")
	case agent.TokenExpiring:
		remaining := time.Until(st.ExpiresAt)
		days := int(remaining.Hours() / 24)
		logWarning("Token expires in %d days (%s)", days, st.ExpiresAt.Format("2006-01-02"))
		fmt.Printf("  Stored: %s\n", st.CreatedAt.Format("2006-01-02"))
		fmt.Println("  Consider regenerating: claude setup-token")
	case agent.TokenValid:
		remaining := time.Until(st.ExpiresAt)
		days := int(remaining.Hours() / 24)
		logSuccess("Token valid (%d days remaining)", days)
		fmt.Printf("  Stored:  %s\n", st.CreatedAt.Format("2006-01-02"))
		fmt.Printf("  Expires: %s\n", st.ExpiresAt.Format("2006-01-02"))
	}

	return nil
}

func runClaudeTokenRemove(cmd *cobra.Command, args []string) error {
	store := claudeTokenStore()
	if err := store.Remove(); err != nil {
		return fmt.Errorf("failed to remove token: %w", err)
	}
	logSuccess("Token removed")
	return nil
}
