version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: standard
  enable:
    - misspell
    - unconvert
    - unparam
    - gosec
    - prealloc

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false

    govet:
      enable-all: true
      disable:
        - fieldalignment

    gosec:
      excludes:
        - G104
        - G304

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - gosec

      - linters:
          - unparam
        text: "always receives"

formatters:
  enable:
    - gofmt
    - goimports

  settings:
    goimports:
      local-prefixes:
        - github.com/firefly-engineering/firefly-forage
