# Generate skill injection content for .claude/forage-skills.md
{ lib }:
{
  template,
  sandboxName,
}:
let
  agentNames = lib.attrNames template.agents;
  agentList =
    if agentNames == [ ] then
      "No agents configured"
    else
      lib.concatMapStringsSep "\n" (name: "- `${name}` - AI coding agent") agentNames;

  networkDesc =
    {
      full = "Full internet access";
      restricted = "Restricted to allowed hosts: ${lib.concatStringsSep ", " template.allowedHosts}";
      none = "No network access (air-gapped)";
    }
    .${template.network};
in
''
  # Forage Sandbox Skills

  You are running inside a Firefly Forage sandbox named `${sandboxName}`.

  ## Environment

  - **Workspace**: `/workspace` (your working directory)
  - **Network**: ${networkDesc}
  - **Session**: tmux session `forage` (persistent across reconnections)

  ## Available Agents

  ${agentList}

  ## Sandbox Constraints

  - The root filesystem is ephemeral (tmpfs) - changes outside /workspace are lost on restart
  - `/nix/store` is read-only (shared from host)
  - `/workspace` is your persistent working directory
  - Secrets are mounted read-only at `/run/secrets/`

  ## Tips

  - Use `tmux` for long-running processes - your session persists across SSH disconnections
  - All project work should be done in `/workspace`
  - The sandbox can be reset with `forage-ctl reset ${sandboxName}` from the host

  ## Sub-Agent Spawning

  When spawning sub-agents (e.g., with Claude Code's Task tool), be aware:
  - Sub-agents share this same sandbox environment
  - Use tmux windows/panes for parallel agent work
  - Each sub-agent has access to the same workspace and tools

  ---
  *This file is auto-generated by Firefly Forage. Do not edit manually.*
''
